(function () {
  if (!document.body.classList.contains("admin-page")) return;
  const state={projects:[],skills:[],experience:[],services:[],social:[],profile:null,settings:null,editId:null,modalType:null};
  const tableEmpty = text => `<tr><td colspan="6" class="loading-row">${text}</td></tr>`;
  const input = (name, value) => { const el=ui.$(`#modal-form [name="${name}"]`); if(!el)return; if(el.type==="checkbox")el.checked=Boolean(value); else el.value=Array.isArray(value)?value.join(", "):(value ?? ""); };
  const dateRange = item => `${ui.formatDate(item.start_date)} — ${ui.formatDate(item.end_date,item.is_current)}`;
  async function boot() {
    const allowed=await authApi.requireAdmin(); if(!allowed)return;
    if(!portfolio.configured)ui.$("#setup-banner")?.classList.remove("hidden");
    const [projects,skills,experience,services,social,profile,settings]=await Promise.all([db.list("projects","*",{order:"sort_order"}),skillsApi.list(),experienceApi.list(),servicesApi.list(),db.list("social_links","*",{order:"sort_order"}),profileApi.get(),db.list("site_settings","*")]);
    state.projects=projects.data||[];state.skills=skills;state.experience=experience;state.services=services;state.social=social.data||[];state.profile=profile;state.settings=settings.data?.[0]||{site_title:"Alex Morgan — Creative Developer",site_description:"",accent_color:"#e7f25c",contact_form_mode:"mailto"};
    const profileImageField=ui.$("#profile-form [name=avatar_url]")?.parentElement;
    if(profileImageField && !ui.$("#profile-form [name=avatar_file]")) profileImageField.insertAdjacentHTML("afterend",'<label>Upload profile image<input name="avatar_file" type="file" accept="image/jpeg,image/png,image/webp"></label>');
    fillProfile();fillSettings();renderAll();bind();
  }
  function fillProfile(){const form=ui.$("#profile-form");if(!form)return;Object.entries(state.profile||{}).forEach(([key,val])=>{const field=form.elements[key];if(field)field.value=val??""});ui.$("#admin-name").textContent=state.profile?.full_name||"Admin";ui.$("#admin-avatar").textContent=(state.profile?.full_name||"AM").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}
  function fillSettings(){const form=ui.$("#settings-form");if(!form)return;Object.entries(state.settings||{}).forEach(([key,val])=>{const field=form.elements[key];if(field)field.value=val??""})}
  function renderAll(){renderStats();renderRecent();renderProjects();renderSkills();renderExperience();renderServices();renderSocial();renderMedia()}
  function renderStats(){ui.$("#stat-projects").textContent=state.projects.length;ui.$("#stat-published").textContent=state.projects.filter(x=>x.status==="published").length;ui.$("#stat-skills").textContent=state.skills.length;ui.$("#stat-experience").textContent=state.experience.length;ui.$("#today-label").textContent=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date())}
  function renderRecent(){const target=ui.$("#recent-projects");if(!target)return;target.innerHTML=state.projects.slice().sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).slice(0,5).map(item=>`<div class="recent-project"><span class="mini-thumb" ${item.thumbnail_url?`style="background-image:url('${ui.esc(item.thumbnail_url)}')"`:""}></span><span><strong>${ui.esc(item.title)}</strong><small>${ui.esc(item.category||"Other")}</small></span><span class="status-badge ${item.status==="draft"?"draft":""}">${ui.esc(item.status||"draft")}</span></div>`).join("")||`<div class="empty-admin">No projects yet.</div>`}
  function renderProjects(){const target=ui.$("#admin-projects-table");if(!target)return;const term=(ui.$("#admin-project-search")?.value||"").toLowerCase();let list=state.projects.filter(p=>`${p.title} ${p.category} ${(p.technologies||[]).join(" ")}`.toLowerCase().includes(term));const sort=ui.$("#project-sort")?.value||"newest";list.sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="oldest"?new Date(a.created_at||0)-new Date(b.created_at||0):sort==="featured"?Number(b.featured)-Number(a.featured):sort==="status"?String(b.status).localeCompare(String(a.status)):new Date(b.created_at||0)-new Date(a.created_at||0));target.innerHTML=list.map(p=>`<tr><td><strong>${ui.esc(p.title)}</strong><small>${ui.esc(p.slug||"")}</small></td><td>${ui.esc(p.category||"—")}</td><td><span class="status-badge ${p.status==="draft"?"draft":""}">${ui.esc(p.status||"draft")}</span></td><td>${p.featured?"Yes":"—"}</td><td><div class="table-actions"><button class="table-action" data-edit-project="${ui.esc(p.id)}">Edit</button><button class="table-action delete" data-delete-project="${ui.esc(p.id)}">Delete</button></div></td></tr>`).join("")||tableEmpty("No projects match your search.")}
  function renderSkills(){const target=ui.$("#skills-table");if(!target)return;target.innerHTML=state.skills.map(s=>`<tr><td><strong>${ui.esc(s.name)}</strong></td><td>${ui.esc(s.category)}</td><td>${ui.esc(s.level||"—")}</td><td>${s.sort_order??"—"}</td><td><div class="table-actions"><button class="table-action" data-edit-skill="${ui.esc(s.id)}">Edit</button><button class="table-action delete" data-delete-skill="${ui.esc(s.id)}">Delete</button></div></td></tr>`).join("")||tableEmpty("No skills added.")}
  function renderExperience(){const target=ui.$("#experience-table");if(!target)return;target.innerHTML=state.experience.map(item=>`<tr><td><strong>${ui.esc(item.position)}</strong></td><td>${ui.esc(item.company)}</td><td>${dateRange(item)}</td><td>${item.is_current?"Yes":"—"}</td><td><div class="table-actions"><button class="table-action" data-edit-experience="${ui.esc(item.id)}">Edit</button><button class="table-action delete" data-delete-experience="${ui.esc(item.id)}">Delete</button></div></td></tr>`).join("")||tableEmpty("No experience added.")}
  function renderServices(){const target=ui.$("#services-table");if(!target)return;target.innerHTML=state.services.map(item=>`<tr><td><strong>${ui.esc(item.title)}</strong></td><td>${ui.esc(item.description).slice(0,54)}${item.description?.length>54?"…":""}</td><td>${item.featured?"Yes":"—"}</td><td><div class="table-actions"><button class="table-action" data-edit-service="${ui.esc(item.id)}">Edit</button><button class="table-action delete" data-delete-service="${ui.esc(item.id)}">Delete</button></div></td></tr>`).join("")||tableEmpty("No services added.")}
  function renderSocial(){const target=ui.$("#social-table");if(!target)return;target.innerHTML=state.social.map(item=>`<tr><td><strong>${ui.esc(item.platform)}</strong></td><td>${ui.esc(item.url)}</td><td>${item.is_visible?"Visible":"Hidden"}</td><td><div class="table-actions"><button class="table-action" data-edit-social="${ui.esc(item.id)}">Edit</button><button class="table-action delete" data-delete-social="${ui.esc(item.id)}">Delete</button></div></td></tr>`).join("")||tableEmpty("No links added.")}
  async function renderMedia(){const target=ui.$("#media-grid");if(!target)return;if(!portfolio.configured){target.innerHTML=`<div class="empty-admin">Configure Supabase to browse your media library.</div>`;return}try{const items=await mediaApi.list();target.innerHTML=items.map(item=>`<figure class="media-item"><img src="${ui.esc(item.url)}" alt="${ui.esc(item.name)}" loading="lazy"><figcaption><span>${ui.esc(item.name)}</span><span class="media-actions"><button data-copy-url="${ui.esc(item.url)}">Copy URL</button><button class="table-action delete" data-delete-media="${ui.esc(item.path)}">Delete</button></span></figcaption></figure>`).join("")||`<div class="empty-admin">Your media library is empty.</div>`}catch(e){target.innerHTML=`<div class="empty-admin">Unable to load media right now.</div>`}}
  function projectFields(){return `<div class="form-row"><label>Project title<input name="title" required></label><label>Category<select name="category"><option>Web</option><option>UI/UX</option><option>Mobile</option><option>Other</option></select></label></div><label>Description<textarea name="description" rows="4" required></textarea></label><div class="form-row"><label>Image URL<input name="thumbnail_url" type="url" placeholder="Optional https://..."></label><label>Upload image<input name="image_file" type="file" accept="image/jpeg,image/png,image/webp"><small class="file-preview" id="project-file-preview">JPG, PNG, WEBP · max 5MB</small></label></div><label>Technologies <span class="field-hint">(comma separated)</span><input name="technologies" placeholder="HTML, CSS, JavaScript"></label><div class="form-row"><label>Live demo URL<input name="demo_url" type="url" placeholder="Optional https://..."></label><label>GitHub URL<input name="github_url" type="url" placeholder="Optional https://github.com/..."></label></div><div class="form-row"><label>Status<select name="status"><option value="published">Published</option><option value="draft">Draft</option></select></label><label>Sort order<input name="sort_order" type="number" min="0" value="1"></label></div><label class="checkbox-label"><input name="featured" type="checkbox"> Feature this project</label><button class="button button-primary" type="submit">Save project <span>↗</span></button>`}
  function socialFields(){return `<div class="form-row"><label>Platform<input name="platform" required placeholder="LinkedIn"></label><label>Short icon<input name="icon" placeholder="in"></label></div><label>URL<input name="url" type="url" required placeholder="https://..."></label><label class="checkbox-label"><input name="is_visible" type="checkbox" checked> Show on public site</label><label>Sort order<input name="sort_order" type="number" min="0" value="1"></label><button class="button button-primary" type="submit">Save link <span>↗</span></button>`}
  function openModal(type,id=null){state.modalType=type;state.editId=id;const title={project:"project",skill:"skill",experience:"experience",service:"service",social:"social link"}[type];const forms={project:projectFields,skill:()=>skillsApi.fields,experience:()=>experienceApi.fields,service:()=>servicesApi.fields,social:socialFields};ui.$("#modal-kicker").textContent=id?"Edit content":"New content";ui.$("#modal-title").textContent=`${id?"Edit":"Add"} ${title}`;ui.$("#modal-form").innerHTML=forms[type]();ui.$("#modal-backdrop").classList.remove("hidden");if(id){const source={project:state.projects,skill:state.skills,experience:state.experience,service:state.services,social:state.social}[type].find(x=>String(x.id)===String(id));if(source)Object.keys(source).forEach(key=>input(key,source[key]))}const file=ui.$("#modal-form [name=image_file]");file?.addEventListener("change",e=>{const selected=e.target.files[0],preview=ui.$("#project-file-preview");if(preview)preview.textContent=selected?`${selected.name} · ${(selected.size/1024/1024).toFixed(2)} MB`:"";});ui.$("#modal-form [name=title],#modal-form [name=name],#modal-form [name=platform]")?.focus()}
  function closeModal(){ui.$("#modal-backdrop").classList.add("hidden");state.editId=null;state.modalType=null}
  async function submitModal(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),button=form.querySelector("button[type=submit]");ui.setBusy(button,true,"Saving…");try{let payload={...data};if(state.modalType==="project"){if(data.image_file?.size){const upload=await mediaApi.upload(data.image_file,"projects");payload.thumbnail_url=upload.publicUrl}delete payload.image_file;payload.slug=ui.slugify(data.title);payload.technologies=String(data.technologies||"").split(",").map(x=>x.trim()).filter(Boolean);payload.featured=form.elements.featured.checked;payload.sort_order=Number(data.sort_order||0)}if(state.modalType==="experience"){payload.technologies=String(data.technologies||"").split(",").map(x=>x.trim()).filter(Boolean);payload.is_current=form.elements.is_current.checked;payload.end_date=payload.is_current?null:(payload.end_date||null);payload.sort_order=Number(data.sort_order||0)}if(state.modalType==="skill")payload.sort_order=Number(data.sort_order||0);if(state.modalType==="service"){payload.featured=form.elements.featured.checked;payload.sort_order=Number(data.sort_order||0)}if(state.modalType==="social"){payload.is_visible=form.elements.is_visible.checked;payload.sort_order=Number(data.sort_order||0)}const api={project:projectApi,skill:skillsApi,experience:experienceApi,service:servicesApi,social:{save:(id,p)=>id?db.update("social_links",id,p):db.insert("social_links",p)}}[state.modalType];const result=await api.save(state.editId,payload);if(result.error)throw result.error;ui.toast(`${titleCase(state.modalType)} ${state.editId?"updated":"created"} successfully.`);closeModal();await refresh();}catch(e){ui.toast(e.message?.includes("image")?e.message:"Unable to save this item. Please try again.","error");console.error(e)}ui.setBusy(button,false)}
  function titleCase(value){return value[0].toUpperCase()+value.slice(1)}
  async function refresh(){const [p,s,e,v,l]=await Promise.all([db.list("projects","*",{order:"sort_order"}),skillsApi.list(),experienceApi.list(),servicesApi.list(),db.list("social_links","*",{order:"sort_order"})]);state.projects=p.data||[];state.skills=s;state.experience=e;state.services=v;state.social=l.data||[];renderAll()}
  async function removeItem(table,id,type){if(!confirm(`Delete this ${type}? This cannot be undone.`))return;try{const result=await db.remove(table,id);if(result.error)throw result.error;ui.toast(`${titleCase(type)} deleted successfully.`);await refresh()}catch(e){ui.toast("Unable to delete this item. Please try again.","error");console.error(e)}}
  function bind(){ui.$$("[data-panel]").forEach(button=>button.addEventListener("click",()=>{ui.$$("[data-panel]").forEach(x=>x.classList.remove("active"));button.classList.add("active");ui.$$(".admin-panel").forEach(x=>x.classList.remove("active"));ui.$(`#panel-${button.dataset.panel}`).classList.add("active");ui.$("#panel-title").textContent=button.textContent.trim();ui.$("#admin-sidebar").classList.remove("open")}));ui.$$("[data-open-project]").forEach(b=>b.addEventListener("click",()=>openModal("project")));ui.$$("[data-open-skill]").forEach(b=>b.addEventListener("click",()=>openModal("skill")));ui.$$("[data-open-experience]").forEach(b=>b.addEventListener("click",()=>openModal("experience")));ui.$$("[data-open-service]").forEach(b=>b.addEventListener("click",()=>openModal("service")));ui.$$("[data-open-social]").forEach(b=>b.addEventListener("click",()=>openModal("social")));ui.$("#modal-close").addEventListener("click",closeModal);ui.$("#modal-backdrop").addEventListener("click",e=>{if(e.target===e.currentTarget)closeModal()});ui.$("#modal-form").addEventListener("submit",submitModal);ui.$("#admin-project-search").addEventListener("input",renderProjects);ui.$("#project-sort").addEventListener("change",renderProjects);ui.$("#sidebar-open").addEventListener("click",()=>ui.$("#admin-sidebar").classList.add("open"));ui.$("#sidebar-close").addEventListener("click",()=>ui.$("#admin-sidebar").classList.remove("open"));ui.$("#logout-button").addEventListener("click",async()=>{if(!confirm("Log out of your dashboard?"))return;if(portfolio.configured)await portfolio.client.auth.signOut();sessionStorage.removeItem("demo-admin");location.href="login.html"});ui.$("#profile-form").addEventListener("submit",saveProfile);ui.$("#settings-form").addEventListener("submit",saveSettings);ui.$("#media-upload").addEventListener("change",uploadMedia);ui.$("#admin-projects-table").addEventListener("click",handleTableAction);ui.$("#skills-table").addEventListener("click",handleTableAction);ui.$("#experience-table").addEventListener("click",handleTableAction);ui.$("#services-table").addEventListener("click",handleTableAction);ui.$("#social-table").addEventListener("click",handleTableAction);ui.$("#media-grid").addEventListener("click",async e=>{const copyBtn=e.target.closest("[data-copy-url]");if(copyBtn){await navigator.clipboard.writeText(copyBtn.dataset.copyUrl);ui.toast("Image URL copied.");return}const delBtn=e.target.closest("[data-delete-media]");if(delBtn){if(!confirm("Delete this image? This cannot be undone."))return;try{const result=await mediaApi.remove(delBtn.dataset.deleteMedia);if(result.error)throw result.error;ui.toast("Image deleted.");await renderMedia()}catch(err){ui.toast("Unable to delete this image.","error");console.error(err)}}})}
  async function handleTableAction(event){const button=event.target.closest("button");if(!button)return;const match=Object.entries(button.dataset).find(([key])=>key.startsWith("edit")||key.startsWith("delete"));if(!match)return;const [key,id]=match,type=key.replace(/^(edit|delete)/,"").toLowerCase();if(key.startsWith("edit"))openModal(type,id);else removeItem(type==="project"?"projects":type==="skill"?"skills":type==="experience"?"experiences":type==="service"?"services":"social_links",id,type)}
  async function saveProfile(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector("button"),payload=Object.fromEntries(new FormData(form));payload.experience_years=Number(payload.experience_years||0);if(payload.avatar_file?.size){try{const upload=await mediaApi.upload(payload.avatar_file,"profile");payload.avatar_url=upload.publicUrl}catch(e){ui.toast(e.message,"error");return}}delete payload.avatar_file;ui.setBusy(button,true,"Saving…");try{const r=await profileApi.save(state.profile.id,payload);if(r.error)throw r.error;Object.assign(state.profile,payload);ui.toast("Profile updated successfully.");fillProfile()}catch(e){ui.toast("Unable to save your profile. Please try again.","error");console.error(e)}ui.setBusy(button,false)}
  async function saveSettings(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector("button"),payload=Object.fromEntries(new FormData(form));ui.setBusy(button,true,"Saving…");try{const r=state.settings.id?await db.update("site_settings",state.settings.id,payload):await db.insert("site_settings",payload);if(r.error)throw r.error;state.settings={...state.settings,...payload};ui.toast("Settings updated successfully.");if(payload.accent_color)document.documentElement.style.setProperty("--accent",payload.accent_color)}catch(e){ui.toast("Unable to save settings. Please try again.","error");console.error(e)}ui.setBusy(button,false)}
  async function uploadMedia(event){const file=event.target.files[0];if(!file)return;try{const result=await mediaApi.upload(file,"projects");ui.toast("Image uploaded successfully.");if(result.demo)ui.toast("Demo upload is temporary until Supabase is configured.","error");await renderMedia()}catch(e){ui.toast(e.message,"error")}event.target.value=""}
  boot().catch(e=>{ui.toast("Unable to load the dashboard. Please check your setup.","error");console.error(e)});
})();
