(function () {
  const state = { projects:[], filter:"all", search:"" };
  async function loadPublic() {
    const [profiles, projects, skills, experience, services, socials, settings] = await Promise.all([
      db.list("profile_public","*"), projectApi.getProjects(), db.list("skills","*",{order:"sort_order"}), db.list("experiences","*",{order:"sort_order"}), db.list("services","*",{order:"sort_order"}), db.list("social_links","*",{order:"sort_order"}), db.list("site_settings","*")
    ]);
    const person = profiles.data?.[0] || DEMO_PROFILE; state.projects = projects;
    const siteSettings = settings.data?.[0];
    if (siteSettings?.site_title) document.title = siteSettings.site_title;
    if (siteSettings?.site_description) document.querySelector('meta[name="description"]')?.setAttribute("content",siteSettings.site_description);
    if (siteSettings?.accent_color) document.documentElement.style.setProperty("--accent",siteSettings.accent_color);
    const setText = (selector, value) => { const el = ui.$(selector); if (el && value !== undefined && value !== null) el.textContent = value; };
    setText("#hero-location", person.location || "Worldwide"); setText("#hero-bio", person.bio); setText("#about-bio", person.bio); setText("#about-location", person.location); setText("#about-years", String(person.experience_years || 0).padStart(2,"0")); setText("#about-profession", person.profession); setText("#contact-email", person.email || "hello@example.com");
    const email = ui.$("#contact-email"); if (email) email.href = `mailto:${person.email || "hello@example.com"}`;
    if (person.avatar_url) { const portrait = ui.$("#hero-portrait"); portrait.style.backgroundImage = `url("${person.avatar_url}")`; portrait.classList.add("has-photo"); }
    const resume = ui.$("#resume-link"); if (resume && person.resume_url) resume.href = person.resume_url; else if (resume) resume.classList.add("hidden");
    const whatsapp = ui.$("#contact-whatsapp"); if (whatsapp && person.phone) whatsapp.href = `https://wa.me/${String(person.phone).replace(/\D/g,"")}`; else if (whatsapp) whatsapp.classList.add("hidden");
    renderSocials(socials.data || DEMO_SOCIAL); renderSkills(skills.data || []); renderExperience(experience.data || []); renderServices(services.data || []); renderProjects();
  }
  function renderSocials(items) { const target = ui.$("#hero-socials"); if (!target) return; target.innerHTML = items.filter(item=>item.is_visible).map(item=>`<a href="${ui.esc(item.url)}" target="_blank" rel="noopener noreferrer" aria-label="${ui.esc(item.platform)}">${ui.esc(item.icon || item.platform)}</a>`).join(""); }
  function renderSkills(items) { const target = ui.$("#skills-grid"); if (!target) return; const groups = items.reduce((acc,item)=>(acc[item.category || "Other"] ||= []).push(item) && acc,{}); target.innerHTML = Object.entries(groups).map(([category, list])=>`<div class="skill-group"><h3>${ui.esc(category)}</h3>${list.map(item=>`<div class="skill-item"><span>${ui.esc(item.name)}</span><b>${ui.esc(item.level || "Working")}</b></div>`).join("")}</div>`).join("") || `<p class="section-intro">Skills are coming soon.</p>`; }
  function renderExperience(items) { const target = ui.$("#experience-list"); if (!target) return; target.innerHTML = items.map(item=>`<article class="timeline-item"><span class="timeline-date">${ui.formatDate(item.start_date)} — ${ui.formatDate(item.end_date,item.is_current)}</span><h3>${ui.esc(item.position)}</h3><span class="timeline-company">${ui.esc(item.company)} · ${ui.esc(item.location || "Remote")}</span><p>${ui.esc(item.description)}</p><div class="timeline-tech">${(item.technologies || []).map(ui.esc).join(" · ")}</div></article>`).join("") || `<p class="section-intro">Experience is coming soon.</p>`; }
  function renderServices(items) { const target = ui.$("#services-grid"); if (!target) return; target.innerHTML = items.map((item,index)=>`<article class="service-card ${item.featured ? "featured" : ""}"><span class="service-index">0${index+1}</span><div class="service-icon">${ui.esc(item.icon || "◇")}</div><h3>${ui.esc(item.title)}</h3><p>${ui.esc(item.description)}</p></article>`).join(""); }
  function renderProjects() { const target = ui.$("#projects-grid"); if (!target) return; const list = state.projects.filter(item => (state.filter === "all" || item.category === state.filter) && (`${item.title} ${item.category} ${(item.technologies || []).join(" ")}`.toLowerCase().includes(state.search))); target.innerHTML = list.map(projectApi.projectCard).join(""); ui.$("#projects-empty")?.classList.toggle("hidden",list.length>0); }
  function bind() { ui.$("#current-year") && (ui.$("#current-year").textContent = new Date().getFullYear()); ui.$("#menu-toggle")?.addEventListener("click", e=>{const open=ui.$("#site-nav").classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",open)}); ui.$$("#site-nav a").forEach(a=>a.addEventListener("click",()=>ui.$("#site-nav").classList.remove("open"))); ui.$$("#project-filters .filter").forEach(button=>button.addEventListener("click",()=>{ui.$$("#project-filters .filter").forEach(b=>b.classList.remove("active"));button.classList.add("active");state.filter=button.dataset.filter;renderProjects()})); ui.$("#project-search")?.addEventListener("input",e=>{state.search=e.target.value.toLowerCase();renderProjects()}); ui.$("#contact-form")?.addEventListener("submit",e=>{if (CONTACT_FORM.mode === "mailto") return; e.preventDefault(); const form=e.currentTarget;if(CONTACT_FORM.mode==="formspree"&&CONTACT_FORM.formspreeUrl){form.action=CONTACT_FORM.formspreeUrl;form.submit()}else ui.toast("Configure your hosted form provider in js/config.js.","error")}); }
  bind(); if (ui.$("#project-detail-content")) projectApi.loadProjectDetail(); if (ui.$("#projects-grid")) loadPublic().catch(error=>{ui.toast(ui.friendlyError(error),"error")});
})();
